language: ruby

services:
  - mysql

rvm:
  - 2.2

env:
  - REDMINE_VER=3.0.7
  - REDMINE_VER=3.1.6
  - REDMINE_VER=3.2.3
  - REDMINE_VER=3.3.0

before_install:
  - export PLUGIN_NAME=redmine__select2
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME
